# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Dependabot
on:
  schedule:
    - cron: "0 8 * * 1"  # Run at 8 AM UTC on Mondays
  workflow_dispatch: # Allow manual triggering

permissions:
  id-token: write
  contents: write

jobs:
  get-release-branch-names:
    runs-on: ubuntu-latest
    outputs:
      curator: ${{ steps.get-branch.outputs.curator_release_branch }}
    steps:
      - name: Get release branch names
        id: get-branch
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          latest_branch=$(gh api repos/NVIDIA-NeMo/Curator/branches --paginate --jq '.[].name' | 
            grep -E '^r[0-9]+\.[0-9]+\.[0-9]+$' | 
            sort -V | 
            tail -n1)
          echo "curator_release_branch=$latest_branch" >> $GITHUB_OUTPUT

  bump-main:
    needs: [get-release-branch-names]
    uses: ./.github/workflows/_update_dependencies.yml
    with:
      target-branch: main
    secrets:
      PAT: ${{ secrets.PAT }}

  bump-release:
    needs: [get-release-branch-names]
    if: needs.get-release-branch-names.outputs.curator != ''
    uses: ./.github/workflows/_update_dependencies.yml
    with:
      target-branch: ${{ needs.get-release-branch-names.outputs.curator }}
    secrets:
      PAT: ${{ secrets.PAT }}

  notify:
    if: failure()
    runs-on: ubuntu-latest
    needs: [bump-main, bump-release]
    steps:
      - name: Notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_ADMIN: <!subteam^${{ secrets.SLACK_WEBHOOK_ADMIN }}>
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          curl -X POST \
            -H 'Content-type: application/json' \
            --data "{\"text\":\":robot_joy: <https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}|Dependabot workflow> failed. Please fix manually.\n\ncc ${SLACK_WEBHOOK_ADMIN}\"}" \
            $SLACK_WEBHOOK

